name: React CI

on:
  push:
    branches:
      - main        # Trigger on push to the 'main' branch
      - develop     # Trigger on push to the 'develop' branch (optional)
  pull_request:
    branches:
      - main        # Trigger on PR to 'main' branch
      - develop     # Trigger on PR to 'develop' branch (optional)

jobs:
  build:
    runs-on: ubuntu-latest      # Runs on the latest version of Ubuntu

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (using stable version)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Remove test step (since you don't have tests yet)
      # - name: Run tests
      #   run: npm test -- --watchAll=false --ci --reporters=default

      # Step 5: Build the React app
      - name: Build project
        run: npm run build



