name: Trigger auto deployment for githubmyapp

# When this action will be executed
on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/githubmyapp-AutoDeployTrigger.yml'

  workflow_dispatch: # Allows manual trigger

permissions:
  id-token: write   # This permission is required for OIDC authentication
  contents: read    # This permission is needed when GitHub token is used to authenticate with private repos

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write  # This is required for requesting the OIDC JWT Token
      contents: read   # Required when GH token is used to authenticate with a private repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login (via OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GITHUBMYAPP_AZURE_CLIENT_ID }}  # Not required for OIDC login
          tenant-id: ${{ secrets.GITHUBMYAPP_AZURE_TENANT_ID }}  # Not required for OIDC login
          subscription-id: ${{ secrets.GITHUBMYAPP_AZURE_SUBSCRIPTION_ID }}  # Not required for OIDC login
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: githubmyapp.azurecr.io
          registryUsername: ${{ secrets.GITHUBMYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GITHUBMYAPP_REGISTRY_PASSWORD }}
          containerAppName: githubmyapp
          resourceGroup: githubmyapp
          imageToBuild: githubmyapp.azurecr.io/githubmyapp:${{ github.sha }}
