name: Trigger auto deployment for githubmyapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
      - '**'
      - '.github/workflows/githubmyapp-AutoDeployTrigger-fc6c7dfe-b661-462c-848b-937236860629.yml'

  # Allow manual trigger 
  workflow_dispatch:

permissions:
  id-token: write  # Permission to request an ID token for OIDC authentication (needed for Azure login)
  contents: read   # Permission to read repository contents

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is required for requesting the OIDC JWT Token
      contents: read   # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GITHUBMYAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GITHUBMYAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GITHUBMYAPP_AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: true
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfile-path: Dockerfile  # Ensure this points to the correct path if needed
          registryUrl: githubmyapp.azurecr.io
          registryUsername: ${{ secrets.GITHUBMYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GITHUBMYAPP_REGISTRY_PASSWORD }}
          containerAppName: githubmyapp
          resourceGroup: githubmyapp
          imageToBuild: githubmyapp.azurecr.io/githubmyapp:${{ github.sha }}
